project_id = "kqhyjxtylvigrezlxzpl"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.get-purchase-files]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-gamepass-purchase]
    verify_jwt = false
  [functions.verify-gamepass-upgrade]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.save-ticket-panel]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.bot-list-emojis]
    verify_jwt = false
  [functions.admin-link-bot]
    verify_jwt = true
  [functions.roblox-verify]
    verify_jwt = false
  [functions.roblox-group-rank]
    verify_jwt = false

# trigger function deploy
